package com.dotty.mvvmproject.navigation

const val ROUTE_HOME = "homepage"
const val ROUTE_LOGIN = "loginpage"
const val ROUTE_REGISTER = "registerpage"
const val ROUTE_CUSTOMLISTVIEW = "customlistviewpage"
const val ROUTE_RESETPASSWORD = "resetpassword"
const val ROUTE_SPLASH = "splashscreen"
const val ROUTE_DASHBOARD = "dashboardscreen"
const val ROUTE_ABOUT = "aboutscreen"
const val ROUTE_BOOKSPACE = "bookspacescreen"
const val ROUTE_CONTACTUS = "contactscreen"
const val ROUTE_SERVICES = "servicescreen"
const val ROUTE_CONFIRM = "confirmscreen"
const val ROUTE_CONFIRMATION = "confirmation/{selectedDate}/{selectedTime}/{selectedSpaceIndex}"